<a href="https://colab.research.google.com/github/RioVossKernan/Learning-AI/blob/main/FeedForwardNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

# seed random numbers to make calculation
# deterministic (just a good practice)
# for use later in the code
np.random.seed(1)


# DATA GENERATION
# input dataset
numofpoints =8
X = []
X = [[x, 1] for x in range(numofpoints)]
print("\n input ordered pairs \n", X)

# output dataset
y = [2*i + 7 + (np.random.random()-0.5)*2 for i in range(numofpoints)]
print("\n output values \n", y)

# convert lists to numpyArray
X = np.array(X)
y = np.array(y).reshape(-1, 1)    #reshape() rearrages the array. 1 is the number of collumns, -1 means as many rows as neccesary.

# normalize (convert to values between 0 and 1 by dividing all values by the max value)
y_unnormalized = y
y = y / np.max(y)
print("\n input array \n", X)
print("\n output array unnormalized \n", y_unnormalized)
print("\n output array normalized \n", y)



# ALGORITHM
# syn0 = 2*np.random.random((2,1)) - 1
syn0 = [[0.1,],[-0.2,]]
syn0 = np.array(syn0)

NUM_STEPS = 1000000
lr = 0.01
print("\n  synapse 0: \n", syn0)

for iter in range(NUM_STEPS):
    # forward propagation

    # Input -> first layer
    L0 = X

    # Apply weight and bias
    L1 = np.dot(L0,syn0)

    # how much did we miss?
    L1_error = y - L1

    L1_delta = L1_error * lr

    # update weight and bias
    syn0 += np.dot(L0.T,L1_delta)


# RESULTS
denormalSynapse = syn0 * np.max(y_unnormalized)
print( "\n L1  \n ", L1)
print( "\n L1 Error :  \n", L1_error)
print( "\n L1 Delta :  \n", L1_delta)
print( "\n Output After Training (syn0):  \n", syn0)
print("\n De-Normalized Output (denormal_syn0)\n", denormalSynapse)
#best answer w/100000 epoch = (1.92, 6.81)


 input ordered pairs 
 [[0, 1], [1, 1], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1]]

 output values 
 [6.834044009405148, 9.440648986884316, 10.00022874963469, 12.604665145263679, 14.293511781634226, 16.184677189537595, 18.372520422755343, 20.691121454086094]

 input array 
 [[0 1]
 [1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]
 [6 1]
 [7 1]]

 output array unnormalized 
 [[ 6.83404401]
 [ 9.44064899]
 [10.00022875]
 [12.60466515]
 [14.29351178]
 [16.18467719]
 [18.37252042]
 [20.69112145]]

 output array normalized 
 [[0.33028872]
 [0.4562657 ]
 [0.48331014]
 [0.60918231]
 [0.69080411]
 [0.78220396]
 [0.88794223]
 [1.        ]]

  synapse 0: 
 [[ 0.1]
 [-0.2]]

 L1  
  [[0.32897194]
 [0.42212271]
 [0.51527349]
 [0.60842426]
 [0.70157503]
 [0.7947258 ]
 [0.88787658]
 [0.98102735]]

 L1 Error :  
 [[ 1.31677706e-03]
 [ 3.41429840e-02]
 [-3.19633498e-02]
 [ 7.58049756e-04]
 [-1.07709197e-02]
 [-1.25218415e-02]
 [ 6.56487750e-05]
 [ 1.89726514e-02]]

 L1 Delta :  
 [[ 1.31677706e-05]
 [ 3.414298